[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C",
    "link-arg=-fuse-ld=/usr/bin/mold",
    "-C",
    "link-arg=-Wl,--no-rosegment",
]
